version: '3'

services:
  apigetaway:
    container_name: apigetaway
    environment:
    - ASPNETCORE_ENVIRONMENT=Docker
    - ASPNETCORE_URLS=http://+
    image: proxy021/forum1apigeteway:2.0
    ports:
    - '5000:80'
  rabbitmq:
    container_name: rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 60s
      retries: 5
    environment:
    - RABBITMQ_DEFAULT_USER=guest
    - RABBITMQ_DEFAULT_PASS=guest
    image: rabbitmq:latest
    ports:
    - '5672'
  notification:
    container_name: notification
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
    - ASPNETCORE_ENVIRONMENT=Docker
    - ASPNETCORE_URLS=http://+
    - MessageBroker__Host=amqp://rabbitmq:5672
    - MessageBroker-UserName=guest
    - MessageBroker-Password=guest
    image: proxy021/forum1notification:2.0
    ports:
    - '80'
  postgres:
    container_name: postgres
    deploy:
      replicas: 1
      restart_policy:
        condition: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s  
    environment:
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_USER=postgres
    image: postgres:latest
    command: ["postgres","-c", "wal_level=logical", "-c", "max_prepared_transactions=10"]
    ports:
    - '5432:5432'
  comment:
    container_name: comment
    depends_on:
      - postgres
      - rabbitmq
    links:
      - postgres
      - rabbitmq
    environment:
    - AuthServiceIp=http://auth:80
    - ASPNETCORE_ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=Comment;Username=postgres;Password=postgres
    - MessageBroker__Host=amqp://rabbitmq:5672
    - MessageBroker__UserName=guest
    - MessageBroker__Password=guest
    - ASPNETCORE_ENVIRONMENT=Docker
    - ASPNETCORE_URLS=http://+
    image: proxy021/forum1comment:2.0
    ports:
    - '80'
  post:
    container_name: post
    depends_on:
      - postgres
      - rabbitmq
    links:
      - postgres
      - rabbitmq
    environment:
    - AuthServiceIp=http://auth:80
    - ASPNETCORE_ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=Post;Username=postgres;Password=postgres
    - MessageBroker__Host=amqp://rabbitmq:5672
    - MessageBroker-UserName=guest
    - MessageBroker-Password=guest
    - ASPNETCORE_ENVIRONMENT=Docker
    - ASPNETCORE_URLS=http://+
    image: proxy021/forum1post:2.0
    ports:
    - '80'
  identity:
    container_name: identity
    depends_on:
      - postgres
      - rabbitmq
    links:
      - postgres
      - rabbitmq
    environment:
    - AuthServiceIp=http://auth:80
    - ASPNETCORE_ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=Identity;Username=postgres;Password=postgres
    - MessageBroker__Host=amqp://rabbitmq:5672
    - MessageBroker-UserName=guest
    - MessageBroker-Password=guest
    - ASPNETCORE_ENVIRONMENT=Docker
    - ASPNETCORE_URLS=http://+
    image: proxy021/forum1identity:2.0
    ports:
    - '80'
  auth:
    container_name: auth
    depends_on:
      - postgres
      - rabbitmq
    links:
      - postgres
      - rabbitmq
    environment:
    - ImagesFolder=images/
    - ASPNETCORE_ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=Identity;Username=postgres;Password=postgres
    - MessageBroker__Host=amqp://rabbitmq:5672
    - MessageBroker-UserName=guest
    - MessageBroker-Password=guest
    - ASPNETCORE_ENVIRONMENT=Docker
    - ASPNETCORE_URLS=http://+
    image: proxy021/forum1auth:2.0
    ports:
    - '5001:80'
