# #######################################################
# #  ApiGetaway
# #######################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-getaway-deployment
  labels:
    app: apigetawey
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apigeteway
  template:
    metadata:
      labels:
        app: apigeteway
    spec:
      containers:
        - image: proxy021/forum1apigeteway:2.0
          name: apigetaway
          ports:
            - containerPort: 80
          env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Development
          - name: ASPNETCORE_URLS
            value: http://+
---
apiVersion: v1
kind: Service
metadata:
  name: apigeteway
spec:
  selector:
    app: apigeteway
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

---
# #######################################################
# #  Postgres
# #######################################################
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: postgres
  name: postgres
spec:
  containers:
    - args:
        - postgres
        - -c
        - wal_level=logical
        - -c
        - max_prepared_transactions=10
      env:
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_USER
          value: postgres
      image: postgres:latest
      name: postgres
      ports:
        - containerPort: 5432
  restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres
  name: postgres
spec:
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  selector:
    app: postgres
---
# #######################################################
# #  Rabbitmq
# #######################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:latest
        ports:
        - containerPort: 5672
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: guest
        - name: RABBITMQ_DEFAULT_PASS
          value: guest
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  selector:
    app: rabbitmq
  ports:
  - name: amqp
    protocol: TCP
    port: 5672
    targetPort: 5672
  type: ClusterIP
---

# #######################################################
#   Auth
# #######################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  labels:
    app: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - image: proxy021/forum1auth:2.0
          name: auth
          ports:
            - containerPort: 80
          env:
          - name: MessageBroker__Host
            value: "amqp://rabbitmq-service.default.svc.cluster.local:5672"
          - name: ASPNETCORE_ENVIRONMENT
            value: Development
          - name: MessageBroker-UserName
            value: guest
          - name: MessageBroker-Password
            value: guest
          - name: ASPNETCORE_ConnectionStrings__DefaultConnection
            value: Host=postgres.default.svc.cluster.local;Port=5432;Database=Identity;Username=postgres;Password=postgres
          - name: ASPNETCORE_URLS
            value: http://+
          - name: ImagesFolder
            value: "images/"
---
apiVersion: v1
kind: Service
metadata:
  name: auth
spec:
  selector:
    app: auth
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
---
# #######################################################
#   Identity
# #######################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-deployment
  labels:
    app: identity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity
  template:
    metadata:
      labels:
        app: identity
    spec:
      containers:
        - image: proxy021/forum1identity:2.0
          name: identity
          ports:
            - containerPort: 80
          env:
            - name: "AuthServiceIp"
              value: "http://auth.default.svc.cluster.local:80"
            - name: MessageBroker__Host
              value: "amqp://rabbitmq-service.default.svc.cluster.local:5672"
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: MessageBroker-UserName
              value: guest
            - name: ASPNETCORE_ConnectionStrings__DefaultConnection
              value: Host=postgres.default.svc.cluster.local;Port=5432;Database=Identity;Username=postgres;Password=postgres
            - name: MessageBroker-Password
              value: guest
            - name: ASPNETCORE_URLS
              value: http://+
---
apiVersion: v1
kind: Service
metadata:
  name: identity
spec:
  selector:
    app: identity
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
---
# #######################################################
#   Post
# #######################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-deployment
  labels:
    app: post
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post
  template:
    metadata:
      labels:
        app: post
    spec:
      containers:
        - image: proxy021/forum1post:2.0
          name: post
          ports:
            - containerPort: 80
          env:
          - name: "AuthServiceIp"
            value: "http://auth.default.svc.cluster.local:80"
          - name: MessageBroker__Host
            value: "amqp://rabbitmq-service.default.svc.cluster.local:5672"
          - name: ASPNETCORE_ENVIRONMENT
            value: Development
          - name: MessageBroker-UserName
            value: guest
          - name: ASPNETCORE_ConnectionStrings__DefaultConnection
            value: Host=postgres.default.svc.cluster.local;Port=5432;Database=Post;Username=postgres;Password=postgres
          - name: MessageBroker-Password
            value: guest
          - name: ASPNETCORE_URLS
            value: http://+
---
apiVersion: v1
kind: Service
metadata:
  name: post
spec:
  selector:
    app: post
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
---
# #######################################################
#   Comment
# #######################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: comment-deployment
  labels:
    app: comment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comment
  template:
    metadata:
      labels:
        app: comment
    spec:
      containers:
        - image: proxy021/forum1comment:2.0
          name: comment
          ports:
            - containerPort: 80
          env:
          - name: "AuthServiceIp"
            value: "http://auth.default.svc.cluster.local:80"
          - name: MessageBroker__Host
            value: "amqp://rabbitmq-service.default.svc.cluster.local:5672"
          - name: MessageBroker__UserName
            value: guest
          - name: MessageBroker__Password
            value: guest
          - name: ASPNETCORE_ConnectionStrings__DefaultConnection
            value: Host=postgres.default.svc.cluster.local;Port=5432;Database=Comment;Username=postgres;Password=postgres
          - name: ASPNETCORE_ENVIRONMENT
            value: Development
          - name: ASPNETCORE_URLS
            value: http://+

---
apiVersion: v1
kind: Service
metadata:
  name: comment
spec:
  selector:
    app: comment
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
---
 #######################################################
 #  Notification
 #######################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-deployment
  labels:
    app: notification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - image: proxy021/forum1notification:2.0
          name: notification
          ports:
            - containerPort: 80
          env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Development
          - name: ASPNETCORE_URLS
            value: http://+
          - name: MessageBroker__Host
            value: "amqp://rabbitmq-service.default.svc.cluster.local:5672"
          - name: MessageBroker-UserName
            value: guest
          - name: ASPNETCORE_ConnectionStrings__DefaultConnection
            value: Host=postgres.default.svc.cluster.local;Port=5432;Database=Notification;Username=postgres;Password=postgres
          - name: MessageBroker-Password
            value: guest
---
apiVersion: v1
kind: Service
metadata:
  name: notification
spec:
  selector:
    app: notification
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
---
